const species = [
  // Pests
  {
    id: '1',
    name: 'Aphids',
    collections: 'Pests',
    image: require('@/assets/images/pests/aphids.jpg'),
    identification: 'aphidsIdentification',
    damage: 'aphidsDamage',
    physicalControl: 'aphidsPC',
  },
  {
    id: '2',
    name: 'Bean Pod Borer',
    collections: 'Pests',
    image: require('@/assets/images/pests/beanPodBorer.jpg'),
    identification: 'beanPodBorerIdentification',
    damage: 'beanPodBorerDamage',
    physicalControl: 'beanPodBorerPC',
  },
  {
    id: '3',
    name: 'Beet Armyworm',
    collections: 'Pests',
    image: require('@/assets/images/pests/beetArmyworm.jpg'),
    identification: 'beetArmywormIdentification',
    damage: 'beetArmywormDamage',
    physicalControl: 'beetArmywormPC',
  },
  {
    id: '4',
    name: 'Rust Fly',
    collections: 'Pests',
    image: require('@/assets/images/pests/rustFly.jpg'),
    identification: 'rustFlyIdentification',
    damage: 'rustFlyDamage',
    physicalControl: 'rustFlyPC',
  },
  {
    id: '5',
    name: 'Chinese Rose Beetle',
    collections: 'Pests',
    image: require('@/assets/images/pests/chineseRoseBeetle.jpg'),
    identification: 'chineseRoseBeetleIdentification',
    damage: 'chineseRoseBeetleDamage',
    physicalControl: 'chineseRoseBeetlePC',
  },
  {
    id: '6',
    name: 'Colorado Potato Beetle',
    collections: 'Pests',
    image: require('@/assets/images/pests/coloradoPotatoBeetle.jpg'),
    identification: 'coloradoPotatoBeetleIdentification',
    damage: 'coloradoPotatoBeetleDamage',
    physicalControl: 'coloradoPotatoBeetlePC',
  },
  {
    id: '7',
    name: 'Corn Earworm',
    collections: 'Pests',
    image: require('@/assets/images/pests/cornEarworm.jpg'),
    identification: 'cornEarwormIdentification',
    damage: 'cornEarwormDamage',
    physicalControl: 'cornEarwormPC',
  },
  {
    id: '8',
    name: 'Cucumber Beetles',
    collections: 'Pests',
    image: require('@/assets/images/pests/cucumberBeetles.jpg'),
    identification: 'cucumberBeetlesIdentification',
    damage: 'cucumberBeetlesDamage',
    physicalControl: 'cucumberBeetlesPC',
  },
  {
    id: '9',
    name: 'Cutworms',
    collections: 'Pests',
    image: require('@/assets/images/pests/cutworms.jpg'),
    identification: 'cutwormsIdentification',
    damage: 'cutwormsDamage',
    physicalControl: 'cutwormsPC',
  },
  {
    id: '10',
    name: 'Diamondback Moth',
    collections: 'Pests',
    image: require('@/assets/images/pests/diamondbackMoth.jpg'),
    identification: 'diamondbackMothIdentification',
    damage: 'diamondbackMothDamage',
    physicalControl: 'diamondbackMothPC',
  },
  {
    id: '11',
    name: 'Flea Beetles',
    collections: 'Pests',
    image: require('@/assets/images/pests/fleaBeetles.jpg'),
    identification: 'fleaBeetlesIdentification',
    damage: 'fleaBeetlesDamage',
    physicalControl: 'fleaBeetlesPC',
  },
  {
    id: '12',
    name: 'Grasshoppers',
    collections: 'Pests',
    image: require('@/assets/images/pests/grasshoppers.jpg'),
    identification: 'grasshoppersIdentification',
    damage: 'grasshoppersDamage',
    physicalControl: 'grasshoppersPC',
  },
  {
    id: '13',
    name: 'Hornworms',
    collections: 'Pests',
    image: require('@/assets/images/pests/hornworms.jpg'),
    identification: 'hornwormsIdentification',
    damage: 'hornwormsDamage',
    physicalControl: 'hornwormsPC',
  },
  {
    id: '14',
    name: 'Japanese Beetle',
    collections: 'Pests',
    image: require('@/assets/images/pests/japaneseBeetle.jpg'),
    identification: 'japaneseBeetleIdentification',
    damage: 'japaneseBeetleDamage',
    physicalControl: 'japaneseBeetlePC',
  },
  {
    id: '15',
    name: 'Large Cabbage White',
    collections: 'Pests',
    image: require('@/assets/images/pests/largeCabbageWhite.jpg'),
    identification: 'largeCabbageWhiteIdentification',
    damage: 'largeCabbageWhiteDamage',
    physicalControl: 'largeCabbageWhitePC',
  },
  {
    id: '16',
    name: 'Leafhopper',
    collections: 'Pests',
    image: require('@/assets/images/pests/leafhopper.jpg'),
    identification: 'leafhopperIdentification',
    damage: 'leafhopperDamage',
    physicalControl: 'leafhopperPC',
  },
  {
    id: '17',
    name: 'Leafminers',
    collections: 'Pests',
    image: require('@/assets/images/pests/leafminers.jpg'),
    identification: 'leafminersIdentification',
    damage: 'leafminersDamage',
    physicalControl: 'leafminersPC',
  },
  {
    id: '18',
    name: 'Leafroller',
    collections: 'Pests',
    image: require('@/assets/images/pests/leafroller.jpg'),
    identification: 'leafrollerIdentification',
    damage: 'leafrollerDamage',
    physicalControl: 'leafrollerPC',
  },
  {
    id: '19',
    name: 'Loopers',
    collections: 'Pests',
    image: require('@/assets/images/pests/loopers.jpg'),
    identification: 'loopersIdentification',
    damage: 'loopersDamage',
    physicalControl: 'loopersPC',
  },
  {
    id: '20',
    name: 'Maggot',
    collections: 'Pests',
    image: require('@/assets/images/pests/maggot.jpg'),
    identification: 'maggotIdentification',
    damage: 'maggotDamage',
    physicalControl: 'maggotPC',
  },
  {
    id: '21',
    name: 'Mealybugs',
    collections: 'Pests',
    image: require('@/assets/images/pests/mealybugs.jpg'),
    identification: 'mealybugsIdentification',
    damage: 'mealybugsDamage',
    physicalControl: 'mealybugsPC',
  },
  {
    id: '22',
    name: 'Mexican Beetle',
    collections: 'Pests',
    image: require('@/assets/images/pests/mexicanBeetle.jpg'),
    identification: 'mexicanBeetleIdentification',
    damage: 'mexicanBeetleDamage',
    physicalControl: 'mexicanBeetlePC',
  },
  {
    id: '23',
    name: 'Pepper Lace Bug',
    collections: 'Pests',
    image: require('@/assets/images/pests/pepperLaceBug.jpg'),
    identification: 'pepperLaceBugIdentification',
    damage: 'pepperLaceBugDamage',
    physicalControl: 'pepperLaceBugPC',
  },
  {
    id: '24',
    name: 'Persea Mites',
    collections: 'Pests',
    image: require('@/assets/images/pests/perseaMites.jpg'),
    identification: 'perseaMitesIdentification',
    damage: 'perseaMitesDamage',
    physicalControl: 'perseaMitesPC',
  },
  {
    id: '25',
    name: 'Rhinoceros Beetle',
    collections: 'Pests',
    image: require('@/assets/images/pests/rhinocerosBeetle.jpg'),
    identification: 'rhinocerosBeetleIdentification',
    damage: 'rhinocerosBeetleDamage',
    physicalControl: 'rhinocerosBeetlePC',
  },
  {
    id: '26',
    name: 'Root Knot Nematode',
    collections: 'Pests',
    image: require('@/assets/images/pests/rootKnotNematode.jpg'),
    identification: 'rootKnotNematodeIdentification',
    physicalControl: 'rootKnotNematodePC',
  },
  {
    id: '27',
    name: 'Scale Insects',
    collections: 'Pests',
    image: require('@/assets/images/pests/scaleInsects.jpg'),
    identification: 'scaleInsectsIdentification',
    damage: 'scaleInsectsDamage',
    physicalControl: 'scaleInsectsPC',
  },
  {
    id: '28',
    name: 'Skipper',
    collections: 'Pests',
    image: require('@/assets/images/pests/skipper.jpg'),
    identification: 'skipperIdentification',
    damage: 'skipperDamage',
    physicalControl: 'skipperPC',
  },
  {
    id: '29',
    name: 'Slugs and snails',
    collections: 'Pests',
    image: require('@/assets/images/pests/slugs-snails.jpg'),
    identification: 'slugsAndSnailsIdentification',
    damage: 'slugsAndSnailsDamage',
    physicalControl: 'slugsAndSnailsPC',
  },
  {
    id: '30',
    name: 'Spider Mites',
    collections: 'Pests',
    image: require('@/assets/images/pests/spiderMites.jpg'),
    identification: 'spiderMitesIdentification',
    damage: 'spiderMitesDamage',
    physicalControl: 'spiderMitesPC',
  },
  {
    id: '31',
    name: 'Spinach Crown Mite',
    collections: 'Pests',
    image: require('@/assets/images/pests/spinachCrownMite.jpg'),
    identification: 'spinachCrownMiteIdentification',
    damage: 'spinachCrownMiteDamage',
    physicalControl: 'spinachCrownMitePC',
  },
  {
    id: '32',
    name: 'Squash Bug',
    collections: 'Pests',
    image: require('@/assets/images/pests/squashBug.jpg'),
    identification: 'squashBugIdentification',
    damage: 'squashBugDamage',
    physicalControl: 'squashBugPC',
  },
  {
    id: '33',
    name: 'Squash Vine Borer',
    collections: 'Pests',
    image: require('@/assets/images/pests/squashVineBorer.jpg'),
    identification: 'squashVineBorerIdentification',
    damage: 'squashVineBorerDamage',
    physicalControl: 'squashVineBorerPC',
  },
  {
    id: '34',
    name: 'Stinkbugs',
    collections: 'Pests',
    image: require('@/assets/images/pests/stinkbugs.jpg'),
    identification: 'stinkbugsIdentification',
    damage: 'stinkbugsDamage',
    physicalControl: 'stinkbugsPC',
  },
  {
    id: '35',
    name: 'Thrips',
    collections: 'Pests',
    image: require('@/assets/images/pests/thrips.jpg'),
    identification: 'thripsIdentification',
    damage: 'thripsDamage',
    physicalControl: 'thripsPC',
  },
  {
    id: '36',
    name: 'Tree Borer',
    collections: 'Pests',
    image: require('@/assets/images/pests/treeBorer.jpg'),
    identification: 'treeBorerIdentification',
    damage: 'treeBorerDamage',
    physicalControl: 'treeBorerPC',
  },
  {
    id: '37',
    name: 'Weevil',
    collections: 'Pests',
    image: require('@/assets/images/pests/weevil.jpg'),
    identification: 'weevilIdentification',
    damage: 'weevilDamage',
    physicalControl: 'weevilPC',
  },
  {
    id: '38',
    name: 'Whitefly',
    collections: 'Pests',
    image: require('@/assets/images/pests/whiteflies.jpg'),
    identification: 'whitefliesIdentification',
    damage: 'whitefliesDamage',
    physicalControl: 'whitefliesPC',
  },
  {
    id: '39',
    name: 'White Grub',
    collections: 'Pests',
    image: require('@/assets/images/pests/whiteGrub.jpg'),
    identification: 'whiteGrubIdentification',
    damage: 'whiteGrubDamage',
    physicalControl: 'whiteGrubPC',
  },
  {
    id: '40',
    name: 'Wireworms',
    collections: 'Pests',
    image: require('@/assets/images/pests/wireworms.jpg'),
    identification: 'wirewormsIdentification',
    damage: 'wirewormsDamage',
    physicalControl: 'wirewormsPC',
  },

  // Diseases
  {
    id: '41',
    name: 'Alternaria Leaf Spot',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/alternariaLeafSpot.jpg'),
    identification: 'alternariaLeafSpotIdentification',
    physicalControl: 'alternariaLeafSpotPC',
  },
  {
    id: '42',
    name: 'Anthracnose',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/anthracnose.jpg'),
    identification: 'anthracnoseIdentification',
    physicalControl: 'anthracnosePC',
  },
  {
    id: '43',
    name: 'Bacterial Canker',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/bacterialCanker.jpg'),
    identification: 'bacterialCankerIdentification',
    physicalControl: 'bacterialCankerPC',
  },
  {
    id: '44',
    name: 'Bacterial Leaf Spot',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/bacterialLeafSpot.jpg'),
    identification: 'bacterialLeafSpotIdentification',
    physicalControl: 'bacterialLeafSpotPC',
  },
  {
    id: '45',
    name: 'Bacterial Ring Rot',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/bacterialRingRot.jpg'),
    identification: 'bacterialRingRotIdentification',
    physicalControl: 'bacterialRingRotPC',
  },
  {
    id: '46',
    name: 'Bacterial Spot',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/bacterialSpot.jpg'),
    identification: 'bacterialSpotIdentification',
    physicalControl: 'bacterialSpotPC',
  },
  {
    id: '47',
    name: 'Black Rot',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/blackRot.jpg'),
    identification: 'blackRotIdentification',
    physicalControl: 'blackRotPC',
  },
  {
    id: '48',
    name: 'Black Sigatoka',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/blackSigatoka.jpg'),
    identification: 'blackSigatokaIdentification',
    physicalControl: 'blackSigatokaPC',
  },
  {
    id: '49',
    name: 'Black Spot',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/blackSpot.jpg'),
    identification: 'blackSpotIdentification',
    physicalControl: 'blackSpotPC',
  },
  {
    id: '50',
    name: 'Blossom End Rot',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/blossomEndRot.jpg'),
    identification: 'blossomEndRotIdentification',
    physicalControl: 'blossomEndRotPC',
  },
  {
    id: '51',
    name: 'Buckeye Rot',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/buckeyeRot.jpg'),
    identification: 'buckeyeRotIdentification',
    physicalControl: 'buckeyeRotPC',
  },
  {
    id: '52',
    name: 'Cercospora Leaf Blight',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/cercosporaLeafBlight.jpg'),
    identification: 'cercosporaLeafBlightIdentification',
    physicalControl: 'cercosporaLeafBlightPC',
  },
  {
    id: '53',
    name: 'Cercospora Leaf Spot',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/cercosporaLeafSpot.jpg'),
    identification: 'cercosporaLeafSpotIdentification',
    physicalControl: 'cercosporaLeafSpotPC',
  },
  {
    id: '54',
    name: 'Cigar End Rot',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/cigarEndRot.jpg'),
    identification: 'cigarEndRotIdentification',
    physicalControl: 'cigarEndRotPC',
  },
  {
    id: '55',
    name: 'Clubroot',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/clubroot.jpg'),
    identification: 'clubrootIdentification',
    physicalControl: 'clubrootPC',
  },
  {
    id: '56',
    name: 'Cottony Rot',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/cottonyRot.jpg'),
    identification: 'cottonyRotIdentification',
    physicalControl: 'cottonyRotPC',
  },
  {
    id: '57',
    name: 'Damping Off',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/dampingOff.jpg'),
    identification: 'dampingOffIdentification',
    physicalControl: 'dampingOffPC',
  },
  {
    id: '58',
    name: 'Downy Mildew',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/downyMildew.jpg'),
    identification: 'downyMildewIdentification',
    physicalControl: 'downyMildewPC',
  },
  {
    id: '59',
    name: 'Early Blight',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/earlyBlight.jpg'),
    identification: 'earlyBlightIdentification',
    physicalControl: 'earlyBlightPC',
  },
  {
    id: '60',
    name: 'Fusarium Wilt',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/fusariumWilt.jpg'),
    identification: 'fusariumWiltIdentification',
    physicalControl: 'fusariumWiltPC',
  },
  {
    id: '61',
    name: 'Gray Leaf Blight',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/grayLeafBlight.jpg'),
    identification: 'grayLeafBlightIdentification',
    physicalControl: 'grayLeafBlightPC',
  },
  {
    id: '62',
    name: 'Gray Mold',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/grayMold.jpg'),
    identification: 'grayMoldIdentification',
    physicalControl: 'grayMoldPC',
  },
  {
    id: '63',
    name: 'Gummy Stem Blight',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/gummyStemBlight.jpg'),
    identification: 'gummyStemBlightIdentification',
    physicalControl: 'gummyStemBlightPC',
  },
  {
    id: '64',
    name: 'Late Blight',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/lateBlight.jpg'),
    identification: 'lateBlightIdentification',
    physicalControl: 'lateBlightPC',
  },
  {
    id: '65',
    name: 'Mosaic Virus',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/mosaicVirus.jpg'),
    identification: 'mosaicVirusIdentification',
    physicalControl: 'mosaicVirusPC',
  },
  {
    id: '66',
    name: 'Phytophthora Blight',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/phytophthoraBlight.jpg'),
    identification: 'phytophthoraBlightIdentification',
    physicalControl: 'phytophthoraBlightPC',
  },
  {
    id: '67',
    name: 'Phytophthora Fruit Rot',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/phytophthoraFruitRot.jpg'),
    identification: 'phytophthoraFruitRotIdentification',
    physicalControl: 'phytophthoraFruitRotPC',
  },
  {
    id: '68',
    name: 'Powdery Mildew',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/powderyMildew.jpg'),
    identification: 'powderyMildewIdentification',
    physicalControl: 'powderyMildewPC',
  },
  {
    id: '69',
    name: 'Pythium Fruit Rot',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/pythiumFruitRot.jpg'),
    identification: 'pythiumFruitRotIdentification',
    physicalControl: 'pythiumFruitRotPC',
  },
  {
    id: '70',
    name: 'Root Rot',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/rootRot.jpg'),
    identification: 'rootRotIdentification',
    physicalControl: 'rootRotPC',
  },
  {
    id: '71',
    name: 'Rust',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/rust.jpg'),
    identification: 'rustIdentification',
    physicalControl: 'rustPC',
  },
  {
    id: '72',
    name: 'Sooty Mold',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/sootyMold.jpg'),
    identification: 'sootyMoldIdentification',
    physicalControl: 'sootyMoldPC',
  },
  {
    id: '73',
    name: 'Sunblotch',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/sunblotch.jpg'),
    identification: 'sunblotchIdentification',
    physicalControl: 'sunblotchPC',
  },
  {
    id: '74',
    name: 'Tomato Spotted Wilt',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/tomatoSpottedWilt.jpg'),
    identification: 'tomatoSpottedWiltIdentification',
    physicalControl: 'tomatoSpottedWiltPC',
  },
  {
    id: '75',
    name: 'Verticillium Wilt',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/verticilliumWilt.jpg'),
    identification: 'verticilliumWiltIdentification',
    physicalControl: 'verticilliumWiltPC',
  },
  {
    id: '76',
    name: 'White Mold',
    collections: 'Diseases',
    image: require('@/assets/images/diseases/whiteMold.jpg'),
    identification: 'whiteMoldIdentification',
    physicalControl: 'whiteMoldPC',
  },

  // Beneficials
  {
    id: '77',
    name: 'Assassin Bugs',
    collections: 'Beneficial',
    image: require('@/assets/images/beneficial/assassin-bugs.jpg'),
    identification: 'assassinBugsIdentification',
    benefits: 'assassinBugsBenefits',
  },
  {
    id: '78',
    name: 'Bees',
    collections: 'Beneficial',
    image: require('@/assets/images/beneficial/bees.jpg'),
    identification: 'beesIdentification',
    benefits: 'beesBenefits',
  },
  {
    id: '79',
    name: 'Birds',
    collections: 'Beneficial',
    image: require('@/assets/images/beneficial/birds.jpg'),
    identification: 'birdsIdentification',
    benefits: 'birdsBenefits',
  },
  {
    id: '80',
    name: 'Butterflies',
    collections: 'Beneficial',
    image: require('@/assets/images/beneficial/butterflies.jpg'),
    identification: 'butterfliesIdentification',
    benefits: 'butterfliesBenefits',
  },
  {
    id: '81',
    name: 'Earthworms',
    collections: 'Beneficial',
    image: require('@/assets/images/beneficial/earthworms.jpg'),
    identification: 'earthwormsIdentification',
    benefits: 'earthwormsBenefits',
  },
  {
    id: '82',
    name: 'Flies',
    collections: 'Beneficial',
    image: require('@/assets/images/beneficial/flies.jpg'),
    identification: 'fliesIdentification',
    benefits: 'fliesBenefits',
  },
  {
    id: '83',
    name: 'Ground Beetles',
    collections: 'Beneficial',
    image: require('@/assets/images/beneficial/ground-beetles.jpg'),
    identification: 'groundBeetlesIdentification',
    benefits: 'groundBeetlesBenefits',
  },
  {
    id: '84',
    name: 'Lacewings',
    collections: 'Beneficial',
    image: require('@/assets/images/beneficial/lacewings.jpg'),
    identification: 'lacewingsIdentification',
    benefits: 'lacewingsBenefits',
  },
  {
    id: '85',
    name: 'Ladybugs',
    collections: 'Beneficial',
    image: require('@/assets/images/beneficial/ladybugs.jpg'),
    identification: 'ladybugsIdentification',
    benefits: 'ladybugsBenefits',
  },
  {
    id: '86',
    name: 'Spiders',
    collections: 'Beneficial',
    image: require('@/assets/images/beneficial/spiders.jpg'),
    identification: 'spidersIdentification',
    benefits: 'spidersBenefits',
  },
  {
    id: '87',
    name: 'Wasps',
    collections: 'Beneficial',
    image: require('@/assets/images/beneficial/wasps.jpg'),
    identification: 'waspsIdentification',
    benefits: 'waspsBenefits',
  },
];

export default species;
